import{a as h,S as g,i as n}from"./assets/vendor-b11e2a50.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const p="44146221-7800b9e1fc66062c227071918",L="https://pixabay.com/api/";async function m(o,t=1,s=15){try{return(await h.get(L,{params:{key:p,q:o,image_tupe:"photo",orientation:"horizontal",safesearch:!0,page:t,perPage:s}})).data}catch(a){throw console.error("Error fetching images:",a),a}}function b(){document.querySelector(".gallery").innerHTML=""}function y(o){const t=document.querySelector(".gallery"),s=o.map(e=>`
      <div class="gallery-item">
      <a href="${e.largeImageURL}" class="gallery__link">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" class= "gallery-item-img" />
        </a>         
          <ul>
            <li><p>Likes: ${e.likes}</p></li>
            <li><p>Views: ${e.views}</p></li>
            <li><p>Comments: ${e.comments}</p></li>
            <li><p>Downloads: ${e.downloads}</p></li>
          </ul>
      </div>
  `).join("");t.insertAdjacentHTML("beforeend",s),new g(".gallery a",{}).refresh()}const f=document.querySelector("#search-form"),v=f.querySelector('input[name="searchQuery"]'),c=document.querySelector(".load-more"),d=document.querySelector(".loader");let i=1,l="";f.addEventListener("submit",w);c.addEventListener("click",S);async function w(o){if(o.preventDefault(),l=v.value.trim(),!l){n.error({title:"Error",message:"Search query cannot be empty!"});return}f.reset,b(),i=1,c.classList.add("hidden"),d.classList.remove("hidden");try{const t=await m(l,i);t.hits.length===0?n.warning({title:"No Results",message:"No images found for your search query. Please try again!"}):(y(t.hits),t.totalHits>i*15&&c.classList.remove("hidden"))}catch{n.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{d.classList.add("hidden")}}async function S(){i+=1,d.classList.remove("hidden");try{const o=await m(l,i);if(y(o.hits),o.totalHits<=i*15){c.classList.add("hidden"),n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."});const s=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:s,behavior:"smooth"})}}catch{n.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{d.classList.add("hidden")}}
//# sourceMappingURL=commonHelpers.js.map
